name: FastAttentionXML

level: 3
k: 4
top: 15

model:
  hidden_size: 256
  layers_num: 1
  linear_size: [256]
  dropout: 0.5
  emb_trainable: False

cluster:
  max_leaf: 4
  eps: 1e-4
  levels: [8, 10]


train:
  [{batch_size: 40, nb_epoch: 30, swa_warmup: 3},
   {batch_size: 40, nb_epoch: 30, swa_warmup: 2},
   {batch_size: 40, nb_epoch: 30, swa_warmup: 2},
   {batch_size: 40, nb_epoch: 30, swa_warmup: 2},
   {batch_size: 40, nb_epoch: 30, swa_warmup: 2}]

valid:
  batch_size: 40

predict:
  batch_size: 40

path: models

board: runs/FastAttentionXML
